FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa de produção - Nginx
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
# Crie um arquivo nginx.conf na pasta frontend com o conteúdo apropriado
COPY nginx.conf /etc/nginx/conf.d
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 4000
CMD ["nginx", "-g", "daemon off;"]
