FROM node:18-slim

WORKDIR /app

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --only=production

COPY . .

RUN npx prisma generate

ENV PORT=3000
EXPOSE 3000

CMD ["npm", "run", "start"]
